### DISCUSSION TITLE
How do I `get` so it merges the default with the original?

### DISCUSSION THREAD

**Discussion by trajano** [fnando/i18n#86] [Q&A]
I'm using YUP (and YAML) and I was wondering if I can have it such that if I have the following

en.yaml
```yaml
yup:
  mixed:
    default: ${path} is not valid
    required: ${path} is required
  number:
    min: 'Number must be greater than ${min}'
```

fr.yaml
```yaml
yup:
  mixed:
    required: '${path} est un champ obligatoire'
```

That I would get 
```yaml
yup:
  mixed:
    default: ${path} is not valid
    required: '${path} est un champ obligatoire'
  number:
    min: 'Number must be greater than ${min}'
```

when I do something like

```js
  const i18n = new I18n({ en, fr }, { defaultLocale: "en" });
  i18n.enableFallback = true;
  i18n.locale = "fr";
  console.log(i18n.get("yup"));
```

I found that `get` doesn't even handle things the way I expect when I have `i18n.locale = "en-CA"` and I have a partial translation of `yup` I only get the partial
